spring:
  cloud:
    gateway:
      routes:
#        - id: test_route
#          uri: https://www.google.com
#          predicates:
#            - Query=url,google
#        - id: amazon
#          uri: https://www.amazon.com
#          predicates:
#            - Query=url,amazon

        - id: product_route
          uri: lb://happymall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: third_party_route
          uri: lb://happymall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*), /$\{segment}

        - id: order_route
          uri: lb://happymall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: member_route
          uri: lb://happymall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: ware_route
          uri: lb://happymall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: admin_rout
          # lb load balance to renren-fast app
          uri: lb://renren-fast
          predicates:
          # all request start with 'api'
            - Path=/api/**
          filters:
          # /api/captcha.jpg... ==> /renren-fast/captcha.jpg...
            - RewritePath=/api/(?<segment>.*), /renren-fast/$\{segment}

        - id: happymall_host_route
          uri: lb://happymall-product
          predicates:
            - Host=happymall.com, item.happymall.com

        - id: happymall_cart_route
          uri: lb://happymall-cart
          predicates:
            - Host=cart.happymall.com

        - id: happymall_search_route
          uri: lb://happymall-search
          predicates:
            - Host=search.happymall.com

        - id: happymall_order_route
          uri: lb://happymall-order
          predicates:
            - Host=order.happymall.com

        - id: happymall_member_route
          uri: lb://happymall-member
          predicates:
            - Host=member.happymall.com

        - id: happymall_auth_route
          uri: lb://happymall-auth-server
          predicates:
            - Host=auth.happymall.com


#
