spring:
  datasource:
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/happymall_ums
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: happymall-member

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
